"""Updated upload table

Revision ID: a5af61b7111a
Revises: a7cacd7efb25
Create Date: 2024-07-02 19:17:38.246956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5af61b7111a'
down_revision: Union[str, None] = 'a7cacd7efb25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploads', sa.Column('upvotes', sa.Integer(), nullable=True))
    op.add_column('uploads', sa.Column('downvotes', sa.Integer(), nullable=True))
    op.add_column('uploads', sa.Column('elo', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploads', 'elo')
    op.drop_column('uploads', 'downvotes')
    op.drop_column('uploads', 'upvotes')
    # ### end Alembic commands ###
